# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form_MDIMain.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PySide6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1262, 1000)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.mdiArea = QtWidgets.QMdiArea(self.centralwidget)
        self.mdiArea.setGeometry(QtCore.QRect(0, 0, 1280, 720))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mdiArea.sizePolicy().hasHeightForWidth())
        self.mdiArea.setSizePolicy(sizePolicy)
        self.mdiArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.mdiArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        brush = QtGui.QBrush(QtGui.QColor(110, 115, 202))
        brush.setStyle(QtCore.Qt.SolidPattern)
        self.mdiArea.setBackground(brush)
        self.mdiArea.setObjectName("mdiArea")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1262, 22))
        self.menuBar.setObjectName("menuBar")
        self.menuFile = QtWidgets.QMenu(self.menuBar)
        self.menuFile.setObjectName("menuFile")
        self.menuReports = QtWidgets.QMenu(self.menuBar)
        self.menuReports.setObjectName("menuReports")
        self.menuWindows = QtWidgets.QMenu(self.menuBar)
        self.menuWindows.setObjectName("menuWindows")
        self.menuMap = QtWidgets.QMenu(self.menuBar)
        self.menuMap.setObjectName("menuMap")
        self.menuLists = QtWidgets.QMenu(self.menuBar)
        self.menuLists.setObjectName("menuLists")
        self.menuAbout = QtWidgets.QMenu(self.menuBar)
        self.menuAbout.setObjectName("menuAbout")
        self.menuHelp = QtWidgets.QMenu(self.menuBar)
        self.menuHelp.setObjectName("menuHelp")
        self.menuFilter = QtWidgets.QMenu(self.menuBar)
        self.menuFilter.setObjectName("menuFilter")
        self.menuPhotos = QtWidgets.QMenu(self.menuBar)
        self.menuPhotos.setObjectName("menuPhotos")
        self.menuMaps = QtWidgets.QMenu(self.menuBar)
        self.menuMaps.setObjectName("menuMaps")
        self.menuChoropleths = QtWidgets.QMenu(self.menuMaps)
        self.menuChoropleths.setObjectName("menuChoropleths")
        self.menuChoroplethsBySpecies = QtWidgets.QMenu(self.menuChoropleths)
        self.menuChoroplethsBySpecies.setObjectName("menuChoroplethsBySpecies")
        self.menuChoroplethsByChecklists = QtWidgets.QMenu(self.menuChoropleths)
        self.menuChoroplethsByChecklists.setObjectName("menuChoroplethsByChecklists")
        self.menuGraphs = QtWidgets.QMenu(self.menuBar)
        self.menuGraphs.setObjectName("menuGraphs")
        self.menuGraphsSpecies = QtWidgets.QMenu(self.menuGraphs)
        self.menuGraphsSpecies.setObjectName("menuGraphsSpecies")
        self.menuGraphsLocations = QtWidgets.QMenu(self.menuGraphs)
        self.menuGraphsLocations.setObjectName("menuGraphsLocations")
        self.menuGraphsChecklists = QtWidgets.QMenu(self.menuGraphs)
        self.menuGraphsChecklists.setObjectName("menuGraphsChecklists")
        self.menuGraphsTiming = QtWidgets.QMenu(self.menuGraphs)
        self.menuGraphsTiming.setObjectName("menuGraphsTiming")
        MainWindow.setMenuBar(self.menuBar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.dckFilter = QtWidgets.QDockWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dckFilter.sizePolicy().hasHeightForWidth())
        self.dckFilter.setSizePolicy(sizePolicy)
        self.dckFilter.setFeatures(QtWidgets.QDockWidget.DockWidgetFeature.DockWidgetClosable | QtWidgets.QDockWidget.DockWidgetFeature.DockWidgetMovable | QtWidgets.QDockWidget.DockWidgetFeature.DockWidgetFloatable)
        self.dckFilter.setAllowedAreas(QtCore.Qt.LeftDockWidgetArea|QtCore.Qt.RightDockWidgetArea)
        self.dckFilter.setObjectName("dckFilter")
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.dockWidgetContents)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.scrFilter = QtWidgets.QScrollArea(self.dockWidgetContents)
        self.scrFilter.setMinimumSize(QtCore.QSize(0, 0))
        self.scrFilter.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.scrFilter.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.scrFilter.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.scrFilter.setLineWidth(0)
        self.scrFilter.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.scrFilter.setWidgetResizable(True)
        self.scrFilter.setObjectName("scrFilter")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 179, 859))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollAreaWidgetContents.sizePolicy().hasHeightForWidth())
        self.scrollAreaWidgetContents.setSizePolicy(sizePolicy)
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_2.setContentsMargins(3, 3, 3, -1)
        self.verticalLayout_2.setSpacing(3)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frmFilter = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frmFilter.sizePolicy().hasHeightForWidth())
        self.frmFilter.setSizePolicy(sizePolicy)
        self.frmFilter.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frmFilter.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frmFilter.setObjectName("frmFilter")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frmFilter)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lblCountries_2 = QtWidgets.QLabel(self.frmFilter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(QtGui.QFont.Weight.Bold)
        self.lblCountries_2.setFont(font)
        self.lblCountries_2.setObjectName("lblCountries_2")
        self.verticalLayout.addWidget(self.lblCountries_2)
        self.cboRegions = QtWidgets.QComboBox(self.frmFilter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cboRegions.sizePolicy().hasHeightForWidth())
        self.cboRegions.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.cboRegions.setFont(font)
        self.cboRegions.setObjectName("cboRegions")
        self.verticalLayout.addWidget(self.cboRegions)
        self.lblCountries = QtWidgets.QLabel(self.frmFilter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(QtGui.QFont.Weight.Bold)
        self.lblCountries.setFont(font)
        self.lblCountries.setObjectName("lblCountries")
        self.verticalLayout.addWidget(self.lblCountries)
        self.cboCountries = QtWidgets.QComboBox(self.frmFilter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cboCountries.sizePolicy().hasHeightForWidth())
        self.cboCountries.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.cboCountries.setFont(font)
        self.cboCountries.setObjectName("cboCountries")
        self.verticalLayout.addWidget(self.cboCountries)
        self.lblStates = QtWidgets.QLabel(self.frmFilter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(QtGui.QFont.Weight.Bold)
        self.lblStates.setFont(font)
        self.lblStates.setObjectName("lblStates")
        self.verticalLayout.addWidget(self.lblStates)
        self.cboStates = QtWidgets.QComboBox(self.frmFilter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cboStates.sizePolicy().hasHeightForWidth())
        self.cboStates.setSizePolicy(sizePolicy)
        self.cboStates.setObjectName("cboStates")
        self.verticalLayout.addWidget(self.cboStates)
        self.lblCounties = QtWidgets.QLabel(self.frmFilter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(QtGui.QFont.Weight.Bold)
        self.lblCounties.setFont(font)
        self.lblCounties.setObjectName("lblCounties")
        self.verticalLayout.addWidget(self.lblCounties)
        self.cboCounties = QtWidgets.QComboBox(self.frmFilter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cboCounties.sizePolicy().hasHeightForWidth())
        self.cboCounties.setSizePolicy(sizePolicy)
        self.cboCounties.setObjectName("cboCounties")
        self.verticalLayout.addWidget(self.cboCounties)
        self.lblLocations = QtWidgets.QLabel(self.frmFilter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(QtGui.QFont.Weight.Bold)
        self.lblLocations.setFont(font)
        self.lblLocations.setObjectName("lblLocations")
        self.verticalLayout.addWidget(self.lblLocations)
        self.cboLocations = QtWidgets.QComboBox(self.frmFilter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cboLocations.sizePolicy().hasHeightForWidth())
        self.cboLocations.setSizePolicy(sizePolicy)
        self.cboLocations.setObjectName("cboLocations")
        self.verticalLayout.addWidget(self.cboLocations)
        self.lblOrders = QtWidgets.QLabel(self.frmFilter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(QtGui.QFont.Weight.Bold)
        self.lblOrders.setFont(font)
        self.lblOrders.setObjectName("lblOrders")
        self.verticalLayout.addWidget(self.lblOrders)
        self.cboOrders = QtWidgets.QComboBox(self.frmFilter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cboOrders.sizePolicy().hasHeightForWidth())
        self.cboOrders.setSizePolicy(sizePolicy)
        self.cboOrders.setObjectName("cboOrders")
        self.verticalLayout.addWidget(self.cboOrders)
        self.lblFamilies = QtWidgets.QLabel(self.frmFilter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(QtGui.QFont.Weight.Bold)
        self.lblFamilies.setFont(font)
        self.lblFamilies.setObjectName("lblFamilies")
        self.verticalLayout.addWidget(self.lblFamilies)
        self.cboFamilies = QtWidgets.QComboBox(self.frmFilter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cboFamilies.sizePolicy().hasHeightForWidth())
        self.cboFamilies.setSizePolicy(sizePolicy)
        self.cboFamilies.setObjectName("cboFamilies")
        self.verticalLayout.addWidget(self.cboFamilies)
        self.lblSpecies = QtWidgets.QLabel(self.frmFilter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(QtGui.QFont.Weight.Bold)
        self.lblSpecies.setFont(font)
        self.lblSpecies.setObjectName("lblSpecies")
        self.verticalLayout.addWidget(self.lblSpecies)
        self.cboSpecies = QtWidgets.QComboBox(self.frmFilter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cboSpecies.sizePolicy().hasHeightForWidth())
        self.cboSpecies.setSizePolicy(sizePolicy)
        self.cboSpecies.setObjectName("cboSpecies")
        self.verticalLayout.addWidget(self.cboSpecies)
        self.lblCommonNameSearch = QtWidgets.QLabel(self.frmFilter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(QtGui.QFont.Weight.Bold)
        self.lblCommonNameSearch.setFont(font)
        self.lblCommonNameSearch.setObjectName("lblCommonNameSearch")
        self.verticalLayout.addWidget(self.lblCommonNameSearch)
        self.txtCommonNameSearch = QtWidgets.QLineEdit(self.frmFilter)
        self.txtCommonNameSearch.setObjectName("txtCommonNameSearch")
        self.verticalLayout.addWidget(self.txtCommonNameSearch)
        self.lblEndSeasonalRange_2 = QtWidgets.QLabel(self.frmFilter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(QtGui.QFont.Weight.Bold)
        self.lblEndSeasonalRange_2.setFont(font)
        self.lblEndSeasonalRange_2.setObjectName("lblEndSeasonalRange_2")
        self.verticalLayout.addWidget(self.lblEndSeasonalRange_2)
        self.cboDateOptions = QtWidgets.QComboBox(self.frmFilter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cboDateOptions.sizePolicy().hasHeightForWidth())
        self.cboDateOptions.setSizePolicy(sizePolicy)
        self.cboDateOptions.setObjectName("cboDateOptions")
        self.verticalLayout.addWidget(self.cboDateOptions)
        self.cboYear = QtWidgets.QComboBox(self.frmFilter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cboYear.sizePolicy().hasHeightForWidth())
        self.cboYear.setSizePolicy(sizePolicy)
        self.cboYear.setObjectName("cboYear")
        self.cboYear.setVisible(False)
        self.verticalLayout.addWidget(self.cboYear)
        self.lblStartDate = QtWidgets.QLabel(self.frmFilter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(QtGui.QFont.Weight.Bold)
        self.lblStartDate.setFont(font)
        self.lblStartDate.setObjectName("lblStartDate")
        self.verticalLayout.addWidget(self.lblStartDate)
        self.calStartDate = QtWidgets.QDateTimeEdit(self.frmFilter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.calStartDate.sizePolicy().hasHeightForWidth())
        self.calStartDate.setSizePolicy(sizePolicy)
        self.calStartDate.setDateTime(QtCore.QDateTime(QtCore.QDate(2000, 2, 1), QtCore.QTime(0, 0, 0)))
        self.calStartDate.setCalendarPopup(True)
        self.calStartDate.setObjectName("calStartDate")
        self.verticalLayout.addWidget(self.calStartDate)
        self.lblEndDate = QtWidgets.QLabel(self.frmFilter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(QtGui.QFont.Weight.Bold)
        self.lblEndDate.setFont(font)
        self.lblEndDate.setObjectName("lblEndDate")
        self.verticalLayout.addWidget(self.lblEndDate)
        self.calEndDate = QtWidgets.QDateTimeEdit(self.frmFilter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.calEndDate.sizePolicy().hasHeightForWidth())
        self.calEndDate.setSizePolicy(sizePolicy)
        self.calEndDate.setDateTime(QtCore.QDateTime(QtCore.QDate(2000, 2, 1), QtCore.QTime(0, 0, 0)))
        self.calEndDate.setCalendarPopup(True)
        self.calEndDate.setObjectName("calEndDate")
        self.verticalLayout.addWidget(self.calEndDate)
        self.lblEndSeasonalRange_3 = QtWidgets.QLabel(self.frmFilter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(QtGui.QFont.Weight.Bold)
        self.lblEndSeasonalRange_3.setFont(font)
        self.lblEndSeasonalRange_3.setObjectName("lblEndSeasonalRange_3")
        self.verticalLayout.addWidget(self.lblEndSeasonalRange_3)
        self.cboSeasonalRangeOptions = QtWidgets.QComboBox(self.frmFilter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cboSeasonalRangeOptions.sizePolicy().hasHeightForWidth())
        self.cboSeasonalRangeOptions.setSizePolicy(sizePolicy)
        self.cboSeasonalRangeOptions.setObjectName("cboSeasonalRangeOptions")
        self.verticalLayout.addWidget(self.cboSeasonalRangeOptions)
        self.lblStartSeasonalRange = QtWidgets.QLabel(self.frmFilter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(QtGui.QFont.Weight.Bold)
        self.lblStartSeasonalRange.setFont(font)
        self.lblStartSeasonalRange.setObjectName("lblStartSeasonalRange")
        self.verticalLayout.addWidget(self.lblStartSeasonalRange)
        self.frmStartSeasonalRange = QtWidgets.QFrame(self.frmFilter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frmStartSeasonalRange.sizePolicy().hasHeightForWidth())
        self.frmStartSeasonalRange.setSizePolicy(sizePolicy)
        self.frmStartSeasonalRange.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frmStartSeasonalRange.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.frmStartSeasonalRange.setLineWidth(0)
        self.frmStartSeasonalRange.setObjectName("frmStartSeasonalRange")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frmStartSeasonalRange)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.cboStartSeasonalRangeMonth = QtWidgets.QComboBox(self.frmStartSeasonalRange)
        self.cboStartSeasonalRangeMonth.setObjectName("cboStartSeasonalRangeMonth")
        self.horizontalLayout.addWidget(self.cboStartSeasonalRangeMonth)
        self.cboStartSeasonalRangeDate = QtWidgets.QComboBox(self.frmStartSeasonalRange)
        self.cboStartSeasonalRangeDate.setObjectName("cboStartSeasonalRangeDate")
        self.horizontalLayout.addWidget(self.cboStartSeasonalRangeDate)
        self.verticalLayout.addWidget(self.frmStartSeasonalRange)
        self.lblEndSeasonalRange = QtWidgets.QLabel(self.frmFilter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(QtGui.QFont.Weight.Bold)
        self.lblEndSeasonalRange.setFont(font)
        self.lblEndSeasonalRange.setObjectName("lblEndSeasonalRange")
        self.verticalLayout.addWidget(self.lblEndSeasonalRange)
        self.frmEndSeasonalRange = QtWidgets.QFrame(self.frmFilter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frmEndSeasonalRange.sizePolicy().hasHeightForWidth())
        self.frmEndSeasonalRange.setSizePolicy(sizePolicy)
        self.frmEndSeasonalRange.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frmEndSeasonalRange.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.frmEndSeasonalRange.setLineWidth(0)
        self.frmEndSeasonalRange.setObjectName("frmEndSeasonalRange")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frmEndSeasonalRange)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.cboEndSeasonalRangeMonth = QtWidgets.QComboBox(self.frmEndSeasonalRange)
        self.cboEndSeasonalRangeMonth.setObjectName("cboEndSeasonalRangeMonth")
        self.horizontalLayout_2.addWidget(self.cboEndSeasonalRangeMonth)
        self.cboEndSeasonalRangeDate = QtWidgets.QComboBox(self.frmEndSeasonalRange)
        self.cboEndSeasonalRangeDate.setObjectName("cboEndSeasonalRangeDate")
        self.horizontalLayout_2.addWidget(self.cboEndSeasonalRangeDate)
        self.verticalLayout.addWidget(self.frmEndSeasonalRange)
        self.verticalLayout_2.addWidget(self.frmFilter, 0, QtCore.Qt.AlignTop)
        self.scrFilter.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_3.addWidget(self.scrFilter)
        self.dckFilter.setWidget(self.dockWidgetContents)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.dckFilter)
        self.dckPhotoFilter = QtWidgets.QDockWidget(MainWindow)
        self.dckPhotoFilter.setFeatures(QtWidgets.QDockWidget.DockWidgetFeature.DockWidgetClosable | QtWidgets.QDockWidget.DockWidgetFeature.DockWidgetMovable | QtWidgets.QDockWidget.DockWidgetFeature.DockWidgetFloatable)
        self.dckPhotoFilter.setAllowedAreas(QtCore.Qt.LeftDockWidgetArea|QtCore.Qt.RightDockWidgetArea)
        self.dckPhotoFilter.setObjectName("dckPhotoFilter")
        self.dockPhotoWidgetContents = QtWidgets.QWidget()
        self.dockPhotoWidgetContents.setObjectName("dockPhotoWidgetContents")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.dockPhotoWidgetContents)
        self.verticalLayout_4.setContentsMargins(3, 3, 3, 3)
        self.verticalLayout_4.setSpacing(3)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.scrPhotoFilter = QtWidgets.QScrollArea(self.dockPhotoWidgetContents)
        self.scrPhotoFilter.setMinimumSize(QtCore.QSize(0, 0))
        self.scrPhotoFilter.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.scrPhotoFilter.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.scrPhotoFilter.setLineWidth(0)
        self.scrPhotoFilter.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContentsOnFirstShow)
        self.scrPhotoFilter.setWidgetResizable(True)
        self.scrPhotoFilter.setObjectName("scrPhotoFilter")
        self.scrollAreaPhotoWidgetContents = QtWidgets.QWidget()
        self.scrollAreaPhotoWidgetContents.setGeometry(QtCore.QRect(0, 0, 190, 440))
        self.scrollAreaPhotoWidgetContents.setObjectName("scrollAreaPhotoWidgetContents")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.scrollAreaPhotoWidgetContents)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.frmPhotoFilter = QtWidgets.QFrame(self.scrollAreaPhotoWidgetContents)
        self.frmPhotoFilter.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frmPhotoFilter.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frmPhotoFilter.setObjectName("frmPhotoFilter")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frmPhotoFilter)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 8)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.lblSighting = QtWidgets.QLabel(self.frmPhotoFilter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(QtGui.QFont.Weight.Bold)
        self.lblSighting.setFont(font)
        self.lblSighting.setObjectName("lblSighting")
        self.verticalLayout_6.addWidget(self.lblSighting)
        self.frmRatingRange = QtWidgets.QFrame(self.frmPhotoFilter)
        self.frmRatingRange.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frmRatingRange.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.frmRatingRange.setLineWidth(0)
        self.frmRatingRange.setObjectName("frmRatingRange")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frmRatingRange)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.cboStartRatingRange = QtWidgets.QComboBox(self.frmRatingRange)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cboStartRatingRange.sizePolicy().hasHeightForWidth())
        self.cboStartRatingRange.setSizePolicy(sizePolicy)
        self.cboStartRatingRange.setObjectName("cboStartRatingRange")
        self.horizontalLayout_5.addWidget(self.cboStartRatingRange)
        self.cboEndRatingRange = QtWidgets.QComboBox(self.frmRatingRange)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cboEndRatingRange.sizePolicy().hasHeightForWidth())
        self.cboEndRatingRange.setSizePolicy(sizePolicy)
        self.cboEndRatingRange.setObjectName("cboEndRatingRange")
        self.horizontalLayout_5.addWidget(self.cboEndRatingRange)
        self.verticalLayout_6.addWidget(self.frmRatingRange)
        self.lblSpeciesHasPhoto = QtWidgets.QLabel(self.frmPhotoFilter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(QtGui.QFont.Weight.Bold)
        self.lblSpeciesHasPhoto.setFont(font)
        self.lblSpeciesHasPhoto.setObjectName("lblSpeciesHasPhoto")
        self.verticalLayout_6.addWidget(self.lblSpeciesHasPhoto)
        self.cboSpeciesHasPhoto = QtWidgets.QComboBox(self.frmPhotoFilter)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.cboSpeciesHasPhoto.setFont(font)
        self.cboSpeciesHasPhoto.setObjectName("cboSpeciesHasPhoto")
        self.verticalLayout_6.addWidget(self.cboSpeciesHasPhoto)
        self.lblCamera = QtWidgets.QLabel(self.frmPhotoFilter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(QtGui.QFont.Weight.Bold)
        self.lblCamera.setFont(font)
        self.lblCamera.setObjectName("lblCamera")
        self.verticalLayout_6.addWidget(self.lblCamera)
        self.cboCamera = QtWidgets.QComboBox(self.frmPhotoFilter)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.cboCamera.setFont(font)
        self.cboCamera.setObjectName("cboCamera")
        self.verticalLayout_6.addWidget(self.cboCamera)
        self.lblLens = QtWidgets.QLabel(self.frmPhotoFilter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(QtGui.QFont.Weight.Bold)
        self.lblLens.setFont(font)
        self.lblLens.setObjectName("lblLens")
        self.verticalLayout_6.addWidget(self.lblLens)
        self.cboLens = QtWidgets.QComboBox(self.frmPhotoFilter)
        self.cboLens.setObjectName("cboLens")
        self.verticalLayout_6.addWidget(self.cboLens)
        self.lblShutterSpeedRange = QtWidgets.QLabel(self.frmPhotoFilter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(QtGui.QFont.Weight.Bold)
        self.lblShutterSpeedRange.setFont(font)
        self.lblShutterSpeedRange.setObjectName("lblShutterSpeedRange")
        self.verticalLayout_6.addWidget(self.lblShutterSpeedRange)
        self.frmShutterSpeedRange = QtWidgets.QFrame(self.frmPhotoFilter)
        self.frmShutterSpeedRange.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frmShutterSpeedRange.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.frmShutterSpeedRange.setLineWidth(0)
        self.frmShutterSpeedRange.setObjectName("frmShutterSpeedRange")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frmShutterSpeedRange)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 4)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.cboStartShutterSpeedRange = QtWidgets.QComboBox(self.frmShutterSpeedRange)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cboStartShutterSpeedRange.sizePolicy().hasHeightForWidth())
        self.cboStartShutterSpeedRange.setSizePolicy(sizePolicy)
        self.cboStartShutterSpeedRange.setObjectName("cboStartShutterSpeedRange")
        self.horizontalLayout_3.addWidget(self.cboStartShutterSpeedRange)
        self.cboEndShutterSpeedRange = QtWidgets.QComboBox(self.frmShutterSpeedRange)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cboEndShutterSpeedRange.sizePolicy().hasHeightForWidth())
        self.cboEndShutterSpeedRange.setSizePolicy(sizePolicy)
        self.cboEndShutterSpeedRange.setObjectName("cboEndShutterSpeedRange")
        self.horizontalLayout_3.addWidget(self.cboEndShutterSpeedRange)
        self.verticalLayout_6.addWidget(self.frmShutterSpeedRange)
        self.lblApertureRange = QtWidgets.QLabel(self.frmPhotoFilter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(QtGui.QFont.Weight.Bold)
        self.lblApertureRange.setFont(font)
        self.lblApertureRange.setObjectName("lblApertureRange")
        self.verticalLayout_6.addWidget(self.lblApertureRange)
        self.frmApertureRange = QtWidgets.QFrame(self.frmPhotoFilter)
        self.frmApertureRange.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frmApertureRange.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.frmApertureRange.setLineWidth(0)
        self.frmApertureRange.setObjectName("frmApertureRange")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frmApertureRange)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 4)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.cboStartApertureRange = QtWidgets.QComboBox(self.frmApertureRange)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cboStartApertureRange.sizePolicy().hasHeightForWidth())
        self.cboStartApertureRange.setSizePolicy(sizePolicy)
        self.cboStartApertureRange.setObjectName("cboStartApertureRange")
        self.horizontalLayout_4.addWidget(self.cboStartApertureRange)
        self.cboEndApertureRange = QtWidgets.QComboBox(self.frmApertureRange)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cboEndApertureRange.sizePolicy().hasHeightForWidth())
        self.cboEndApertureRange.setSizePolicy(sizePolicy)
        self.cboEndApertureRange.setObjectName("cboEndApertureRange")
        self.horizontalLayout_4.addWidget(self.cboEndApertureRange)
        self.verticalLayout_6.addWidget(self.frmApertureRange)
        self.lblFocalLengthRange = QtWidgets.QLabel(self.frmPhotoFilter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(QtGui.QFont.Weight.Bold)
        self.lblFocalLengthRange.setFont(font)
        self.lblFocalLengthRange.setObjectName("lblFocalLengthRange")
        self.verticalLayout_6.addWidget(self.lblFocalLengthRange)
        self.frmFocalLengthRange = QtWidgets.QFrame(self.frmPhotoFilter)
        self.frmFocalLengthRange.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frmFocalLengthRange.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.frmFocalLengthRange.setLineWidth(0)
        self.frmFocalLengthRange.setObjectName("frmFocalLengthRange")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frmFocalLengthRange)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 4)
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.cboStartFocalLengthRange = QtWidgets.QComboBox(self.frmFocalLengthRange)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cboStartFocalLengthRange.sizePolicy().hasHeightForWidth())
        self.cboStartFocalLengthRange.setSizePolicy(sizePolicy)
        self.cboStartFocalLengthRange.setObjectName("cboStartFocalLengthRange")
        self.horizontalLayout_7.addWidget(self.cboStartFocalLengthRange)
        self.cboEndFocalLengthRange = QtWidgets.QComboBox(self.frmFocalLengthRange)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cboEndFocalLengthRange.sizePolicy().hasHeightForWidth())
        self.cboEndFocalLengthRange.setSizePolicy(sizePolicy)
        self.cboEndFocalLengthRange.setObjectName("cboEndFocalLengthRange")
        self.horizontalLayout_7.addWidget(self.cboEndFocalLengthRange)
        self.verticalLayout_6.addWidget(self.frmFocalLengthRange)
        self.lblISORange = QtWidgets.QLabel(self.frmPhotoFilter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(QtGui.QFont.Weight.Bold)
        self.lblISORange.setFont(font)
        self.lblISORange.setObjectName("lblISORange")
        self.verticalLayout_6.addWidget(self.lblISORange)
        self.frmIsoRange = QtWidgets.QFrame(self.frmPhotoFilter)
        self.frmIsoRange.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frmIsoRange.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.frmIsoRange.setLineWidth(0)
        self.frmIsoRange.setObjectName("frmIsoRange")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frmIsoRange)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 4)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.cboStartIsoRange = QtWidgets.QComboBox(self.frmIsoRange)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cboStartIsoRange.sizePolicy().hasHeightForWidth())
        self.cboStartIsoRange.setSizePolicy(sizePolicy)
        self.cboStartIsoRange.setObjectName("cboStartIsoRange")
        self.horizontalLayout_6.addWidget(self.cboStartIsoRange)
        self.cboEndIsoRange = QtWidgets.QComboBox(self.frmIsoRange)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cboEndIsoRange.sizePolicy().hasHeightForWidth())
        self.cboEndIsoRange.setSizePolicy(sizePolicy)
        self.cboEndIsoRange.setObjectName("cboEndIsoRange")
        self.horizontalLayout_6.addWidget(self.cboEndIsoRange)
        self.verticalLayout_6.addWidget(self.frmIsoRange)
        self.verticalLayout_5.addWidget(self.frmPhotoFilter)
        self.scrPhotoFilter.setWidget(self.scrollAreaPhotoWidgetContents)
        self.verticalLayout_4.addWidget(self.scrPhotoFilter, 0, QtCore.Qt.AlignTop)
        self.dckPhotoFilter.setWidget(self.dockPhotoWidgetContents)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.dckPhotoFilter)
        self.actionOpen = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon_open.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionOpen.setIcon(icon)
        self.actionOpen.setIconVisibleInMenu(False)
        self.actionOpen.setObjectName("actionOpen")
        self.actionExit = QtGui.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionDateTotals = QtGui.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icon_datetotals.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionDateTotals.setIcon(icon1)
        self.actionDateTotals.setIconVisibleInMenu(False)
        self.actionDateTotals.setObjectName("actionDateTotals")
        self.actionLocationTotals = QtGui.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icon_locationtotals.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionLocationTotals.setIcon(icon2)
        self.actionLocationTotals.setIconVisibleInMenu(False)
        self.actionLocationTotals.setObjectName("actionLocationTotals")
        self.actionTileWindows = QtGui.QAction(MainWindow)
        self.actionTileWindows.setObjectName("actionTileWindows")
        self.actionCloseAllWindows = QtGui.QAction(MainWindow)
        self.actionCloseAllWindows.setObjectName("actionCloseAllWindows")
        self.actionCompareLists = QtGui.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icon_compare.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCompareLists.setIcon(icon3)
        self.actionCompareLists.setIconVisibleInMenu(False)
        self.actionCompareLists.setObjectName("actionCompareLists")
        self.actionCascade = QtGui.QAction(MainWindow)
        self.actionCascade.setObjectName("actionCascade")
        self.actionSpecies = QtGui.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icon_bird.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSpecies.setIcon(icon4)
        self.actionSpecies.setIconVisibleInMenu(False)
        self.actionSpecies.setObjectName("actionSpecies")
        self.actionLocations = QtGui.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icon_location.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionLocations.setIcon(icon5)
        self.actionLocations.setIconVisibleInMenu(False)
        self.actionLocations.setObjectName("actionLocations")
        self.actionChecklists = QtGui.QAction(MainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icon_checklists.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionChecklists.setIcon(icon6)
        self.actionChecklists.setIconVisibleInMenu(False)
        self.actionChecklists.setObjectName("actionChecklists")
        self.actionBigReport = QtGui.QAction(MainWindow)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/icon_tripreport.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionBigReport.setIcon(icon7)
        self.actionBigReport.setIconVisibleInMenu(False)
        self.actionBigReport.setObjectName("actionBigReport")
        self.actionStats = QtGui.QAction(MainWindow)
        self.actionStats.setIconVisibleInMenu(False)
        self.actionStats.setObjectName("actionStats")
        self.actionBarGraph = QtGui.QAction(MainWindow)
        self.actionBarGraph.setObjectName("actionBarGraph")
        self.actionCumulativeCurve = QtGui.QAction(MainWindow)
        self.actionCumulativeCurve.setObjectName("actionCumulativeCurve")
        self.actionCumulativeLocations = QtGui.QAction(MainWindow)
        self.actionCumulativeLocations.setObjectName("actionCumulativeLocations")
        self.actionCumulativeFamilies = QtGui.QAction(MainWindow)
        self.actionCumulativeFamilies.setObjectName("actionCumulativeFamilies")
        self.actionHeatmap = QtGui.QAction(MainWindow)
        self.actionHeatmap.setObjectName("actionHeatmap")
        self.actionAccumulation = QtGui.QAction(MainWindow)
        self.actionAccumulation.setObjectName("actionAccumulation")
        self.actionTopLocations = QtGui.QAction(MainWindow)
        self.actionTopLocations.setObjectName("actionTopLocations")
        self.actionYTDReport = QtGui.QAction(MainWindow)
        self.actionYTDReport.setObjectName("actionYTDReport")
        self.actionYTDLocations = QtGui.QAction(MainWindow)
        self.actionYTDLocations.setObjectName("actionYTDLocations")
        self.actionYTDChecklists = QtGui.QAction(MainWindow)
        self.actionYTDChecklists.setObjectName("actionYTDChecklists")
        self.actionTotalChecklists = QtGui.QAction(MainWindow)
        self.actionTotalChecklists.setObjectName("actionTotalChecklists")
        self.actionTotalLocations = QtGui.QAction(MainWindow)
        self.actionTotalLocations.setObjectName("actionTotalLocations")
        self.actionScatter = QtGui.QAction(MainWindow)
        self.actionScatter.setObjectName("actionScatter")
        self.actionPhenology = QtGui.QAction(MainWindow)
        self.actionPhenology.setObjectName("actionPhenology")
        self.actionFOY = QtGui.QAction(MainWindow)
        self.actionFOY.setObjectName("actionFOY")
        self.actionLOY = QtGui.QAction(MainWindow)
        self.actionLOY.setObjectName("actionLOY")
        self.actionLocationScatter = QtGui.QAction(MainWindow)
        self.actionLocationScatter.setObjectName("actionLocationScatter")
        self.actionSpeciesScatter = QtGui.QAction(MainWindow)
        self.actionSpeciesScatter.setObjectName("actionSpeciesScatter")
        self.actionLocationChecklistPie = QtGui.QAction(MainWindow)
        self.actionLocationChecklistPie.setObjectName("actionLocationChecklistPie")
        self.actionFamilyPie = QtGui.QAction(MainWindow)
        self.actionFamilyPie.setObjectName("actionFamilyPie")
        self.actionIndivPie = QtGui.QAction(MainWindow)
        self.actionIndivPie.setObjectName("actionIndivPie")
        self.actionFind = QtGui.QAction(MainWindow)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/icon_find.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionFind.setIcon(icon8)
        self.actionFind.setIconVisibleInMenu(False)
        self.actionFind.setObjectName("actionFind")
        self.actionFamilies = QtGui.QAction(MainWindow)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/icon_families.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionFamilies.setIcon(icon9)
        self.actionFamilies.setIconVisibleInMenu(False)
        self.actionFamilies.setObjectName("actionFamilies")
        self.actionMap = QtGui.QAction(MainWindow)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/icon_map.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionMap.setIcon(icon10)
        self.actionMap.setIconVisibleInMenu(False)
        self.actionMap.setObjectName("actionMap")
        self.actionCreatePDF = QtGui.QAction(MainWindow)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/icon_pdf.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCreatePDF.setIcon(icon11)
        self.actionCreatePDF.setIconVisibleInMenu(False)
        self.actionCreatePDF.setObjectName("actionCreatePDF")
        self.actionPrint = QtGui.QAction(MainWindow)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(":/icon_print.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPrint.setIcon(icon12)
        self.actionPrint.setIconVisibleInMenu(False)
        self.actionPrint.setObjectName("actionPrint")
        self.actionAboutYearbirder = QtGui.QAction(MainWindow)
        self.actionAboutYearbirder.setObjectName("actionAboutYearbirder")
        self.actionUserGuide = QtGui.QAction(MainWindow)
        self.actionUserGuide.setObjectName("actionUserGuide")
        self.actionShowStandardFilter = QtGui.QAction(MainWindow)
        self.actionShowStandardFilter.setObjectName("actionShowStandardFilter")
        self.actionHideStandardFilter = QtGui.QAction(MainWindow)
        self.actionHideStandardFilter.setObjectName("actionHideStandardFilter")
        self.actionClearAllFilters = QtGui.QAction(MainWindow)
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(":/icon_filter.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionClearAllFilters.setIcon(icon13)
        self.actionClearAllFilters.setIconVisibleInMenu(False)
        self.actionClearAllFilters.setObjectName("actionClearAllFilters")
        self.actionSetPhotoFolder = QtGui.QAction(MainWindow)
        self.actionSetPhotoFolder.setObjectName("actionSetPhotoFolder")
        self.actionPhotos = QtGui.QAction(MainWindow)
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(":/icon_camera.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPhotos.setIcon(icon14)
        self.actionPhotos.setIconVisibleInMenu(False)
        self.actionPhotos.setObjectName("actionPhotos")
        self.actionPhotosByFilter = QtGui.QAction(MainWindow)
        self.actionPhotosByFilter.setObjectName("actionPhotosByFilter")
        self.actionSpeciesGallery = QtGui.QAction(MainWindow)
        self.actionSpeciesGallery.setObjectName("actionSpeciesGallery")
        self.actionEditPhotosByFilter = QtGui.QAction(MainWindow)
        self.actionEditPhotosByFilter.setObjectName("actionEditPhotosByFilter")
        self.actionOpenPhotoSettings = QtGui.QAction(MainWindow)
        self.actionOpenPhotoSettings.setObjectName("actionOpenPhotoSettings")
        self.actionAddPhotos = QtGui.QAction(MainWindow)
        self.actionAddPhotos.setObjectName("actionAddPhotos")
        self.actionSavePhotoSettings = QtGui.QAction(MainWindow)
        self.actionSavePhotoSettings.setObjectName("actionSavePhotoSettings")
        self.actionPreferences = QtGui.QAction(MainWindow)
        self.actionPreferences.setObjectName("actionPreferences")
        self.actionUpdateEXIFDataForAllPhotos = QtGui.QAction(MainWindow)
        self.actionUpdateEXIFDataForAllPhotos.setObjectName("actionUpdateEXIFDataForAllPhotos")
        self.actionRenamePhotos = QtGui.QAction(MainWindow)
        self.actionRenamePhotos.setObjectName("actionRenamePhotos")
        self.actionOptimizePhotoSettings = QtGui.QAction(MainWindow)
        self.actionOptimizePhotoSettings.setObjectName("actionOptimizePhotoSettings")
        self.actionShowPhotoFilter = QtGui.QAction(MainWindow)
        self.actionShowPhotoFilter.setObjectName("actionShowPhotoFilter")
        self.actionHidePhotoFilter = QtGui.QAction(MainWindow)
        self.actionHidePhotoFilter.setObjectName("actionHidePhotoFilter")
        self.actionClearPhotoFilter = QtGui.QAction(MainWindow)
        self.actionClearPhotoFilter.setObjectName("actionClearPhotoFilter")
        self.actionClearStandardFilter = QtGui.QAction(MainWindow)
        self.actionClearStandardFilter.setObjectName("actionClearStandardFilter")
        self.actionClose = QtGui.QAction(MainWindow)
        self.actionClose.setObjectName("actionClose")
        self.actionClosePhotoSettings = QtGui.QAction(MainWindow)
        self.actionClosePhotoSettings.setObjectName("actionClosePhotoSettings")
        self.actionUS_States = QtGui.QAction(MainWindow)
        self.actionUS_States.setObjectName("actionUS_States")
        self.actionWorld_Countries = QtGui.QAction(MainWindow)
        self.actionWorld_Countries.setObjectName("actionWorld_Countries")
        self.actionWorld_Subregion_1 = QtGui.QAction(MainWindow)
        self.actionWorld_Subregion_1.setObjectName("actionWorld_Subregion_1")
        self.actionUS_Counties = QtGui.QAction(MainWindow)
        self.actionUS_Counties.setObjectName("actionUS_Counties")
        self.actionCanada_Provinces = QtGui.QAction(MainWindow)
        self.actionCanada_Provinces.setObjectName("actionCanada_Provinces")
        self.actionIndia_States = QtGui.QAction(MainWindow)
        self.actionIndia_States.setObjectName("actionIndia_States")
        self.actionGB_Counties = QtGui.QAction(MainWindow)
        self.actionGB_Counties.setObjectName("actionGB_Counties")
        self.actionUS_States_Checklists = QtGui.QAction(MainWindow)
        self.actionUS_States_Checklists.setObjectName("actionUS_States_Checklists")
        self.actionUS_Counties_Checklists = QtGui.QAction(MainWindow)
        self.actionUS_Counties_Checklists.setObjectName("actionUS_Counties_Checklists")
        self.actionCanada_Provinces_Checklists = QtGui.QAction(MainWindow)
        self.actionCanada_Provinces_Checklists.setObjectName("actionCanada_Provinces_Checklists")
        self.actionIndia_States_Checklists = QtGui.QAction(MainWindow)
        self.actionIndia_States_Checklists.setObjectName("actionIndia_States_Checklists")
        self.actionGB_Counties_Checklists = QtGui.QAction(MainWindow)
        self.actionGB_Counties_Checklists.setObjectName("actionGB_Counties_Checklists")
        self.actionWorld_Countries_Checklists = QtGui.QAction(MainWindow)
        self.actionWorld_Countries_Checklists.setObjectName("actionWorld_Countries_Checklists")
        self.actionGeolocatedPhotos = QtGui.QAction(MainWindow)
        self.actionGeolocatedPhotos.setObjectName("actionGeolocatedPhotos")
        self.actionAnimatedPhotoSequence = QtGui.QAction(MainWindow)
        self.actionAnimatedPhotoSequence.setObjectName("actionAnimatedPhotoSequence")
        self.actionSlideshow = QtGui.QAction(MainWindow)
        self.actionSlideshow.setObjectName("actionSlideshow")
        self.actionYTDPhotos = QtGui.QAction(MainWindow)
        self.actionYTDPhotos.setObjectName("actionYTDPhotos")
        self.actionPhotoPie = QtGui.QAction(MainWindow)
        self.actionPhotoPie.setObjectName("actionPhotoPie")
        self.actionPhotoBar = QtGui.QAction(MainWindow)
        self.actionPhotoBar.setObjectName("actionPhotoBar")
        self.actionPhotoAccumulation = QtGui.QAction(MainWindow)
        self.actionPhotoAccumulation.setObjectName("actionPhotoAccumulation")
        self.actionCumulativePhotos = QtGui.QAction(MainWindow)
        self.actionCumulativePhotos.setObjectName("actionCumulativePhotos")
        self.actionLifeListMap = QtGui.QAction(MainWindow)
        self.actionLifeListMap.setObjectName("actionLifeListMap")
        self.actionFirstSightingsMap = QtGui.QAction(MainWindow)
        self.actionFirstSightingsMap.setObjectName("actionFirstSightingsMap")
        self.actionEffortMap = QtGui.QAction(MainWindow)
        self.actionEffortMap.setObjectName("actionEffortMap")
        self.actionEffortMapByChecklists = QtGui.QAction(MainWindow)
        self.actionEffortMapByChecklists.setObjectName("actionEffortMapByChecklists")
        self.actionSpeciesTotalMap = QtGui.QAction(MainWindow)
        self.actionSpeciesTotalMap.setObjectName("actionSpeciesTotalMap")
        self.actionIndividualsTotalMap = QtGui.QAction(MainWindow)
        self.actionIndividualsTotalMap.setObjectName("actionIndividualsTotalMap")
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionClose)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionOpenPhotoSettings)
        self.menuFile.addAction(self.actionClosePhotoSettings)
        self.menuFile.addAction(self.actionSavePhotoSettings)
        self.menuFileCatalogSeparator = self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionAddPhotos)
        self.menuFile.addAction(self.actionEditPhotosByFilter)
        self.menuFile.addAction(self.actionUpdateEXIFDataForAllPhotos)
        self.menuFile.addAction(self.actionRenamePhotos)
        self.menuFile.addAction(self.actionOptimizePhotoSettings)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionPrint)
        self.menuFile.addAction(self.actionCreatePDF)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionPreferences)
        self.menuFile.addAction(self.actionExit)
        self.menuReports.addAction(self.actionDateTotals)
        self.menuReports.addAction(self.actionLocationTotals)
        self.menuReports.addAction(self.actionCompareLists)
        self.menuReports.addAction(self.actionBigReport)
        self.menuReports.addAction(self.actionStats)
        self.menuGraphsSpecies.addAction(self.actionBarGraph)
        self.menuGraphsSpecies.addAction(self.actionAccumulation)
        self.menuGraphsSpecies.addAction(self.actionCumulativeCurve)
        self.menuGraphsSpecies.addAction(self.actionCumulativeFamilies)
        self.menuGraphsSpecies.addAction(self.actionYTDReport)
        self.menuGraphsSpecies.addAction(self.actionFamilyPie)
        self.menuGraphsSpecies.addAction(self.actionIndivPie)
        self.menuGraphsSpecies.addAction(self.actionSpeciesScatter)
        self.menuGraphsLocations.addAction(self.actionTotalLocations)
        self.menuGraphsLocations.addAction(self.actionCumulativeLocations)
        self.menuGraphsLocations.addAction(self.actionTopLocations)
        self.menuGraphsLocations.addAction(self.actionYTDLocations)
        self.menuGraphsLocations.addAction(self.actionLocationScatter)
        self.menuGraphsLocations.addAction(self.actionLocationChecklistPie)
        self.menuGraphsChecklists.addAction(self.actionTotalChecklists)
        self.menuGraphsChecklists.addAction(self.actionYTDChecklists)
        self.menuGraphsChecklists.addAction(self.actionScatter)
        self.menuGraphsTiming.addAction(self.actionHeatmap)
        self.menuGraphsTiming.addAction(self.actionPhenology)
        self.menuGraphsTiming.addAction(self.actionFOY)
        self.menuGraphsTiming.addAction(self.actionLOY)
        self.menuGraphs.addAction(self.menuGraphsSpecies.menuAction())
        self.menuGraphs.addAction(self.menuGraphsLocations.menuAction())
        self.menuGraphs.addAction(self.menuGraphsChecklists.menuAction())
        self.menuGraphs.addAction(self.menuGraphsTiming.menuAction())
        self.menuWindows.addAction(self.actionTileWindows)
        self.menuWindows.addAction(self.actionCascade)
        self.menuWindows.addAction(self.actionCloseAllWindows)
        self.menuLists.addAction(self.actionSpecies)
        self.menuLists.addAction(self.actionLocations)
        self.menuLists.addAction(self.actionChecklists)
        self.menuLists.addAction(self.actionFamilies)
        self.menuLists.addAction(self.actionPhotos)
        self.menuAbout.addAction(self.actionAboutYearbirder)
        self.menuHelp.addAction(self.actionUserGuide)
        self.menuFilter.addAction(self.actionShowStandardFilter)
        self.menuFilter.addAction(self.actionShowPhotoFilter)
        self.menuFilter.addAction(self.actionHideStandardFilter)
        self.menuFilter.addAction(self.actionHidePhotoFilter)
        self.menuFilter.addSeparator()
        self.menuFilter.addAction(self.actionClearAllFilters)
        self.menuFilter.addAction(self.actionClearStandardFilter)
        self.menuFilter.addAction(self.actionClearPhotoFilter)
        self.menuPhotos.addAction(self.actionPhotosByFilter)
        self.menuPhotos.addAction(self.actionSpeciesGallery)
        self.actionGeolocatedPhotosSeparator = self.menuPhotos.addSeparator()
        self.actionGeolocatedPhotosSeparator.setVisible(False)
        self.menuPhotos.addAction(self.actionGeolocatedPhotos)
        self.actionGeolocatedPhotos.setVisible(False)
        self.menuPhotos.addAction(self.actionAnimatedPhotoSequence)
        self.actionAnimatedPhotoSequence.setVisible(False)
        self.menuPhotos.addAction(self.actionYTDPhotos)
        self.actionYTDPhotos.setVisible(False)
        self.menuPhotos.addAction(self.actionPhotoPie)
        self.actionPhotoPie.setVisible(False)
        self.menuPhotos.addAction(self.actionPhotoBar)
        self.actionPhotoBar.setVisible(False)
        self.menuPhotos.addAction(self.actionPhotoAccumulation)
        self.actionPhotoAccumulation.setVisible(False)
        self.menuPhotos.addAction(self.actionCumulativePhotos)
        self.actionCumulativePhotos.setVisible(False)
        # Slideshow stays last in the Photos menu — do not add items below this line
        self.menuPhotos.addAction(self.actionSlideshow)
        self.actionSlideshow.setVisible(False)
        self.menuChoroplethsBySpecies.addAction(self.actionUS_States)
        self.menuChoroplethsBySpecies.addAction(self.actionUS_Counties)
        self.menuChoroplethsBySpecies.addAction(self.actionCanada_Provinces)
        self.menuChoroplethsBySpecies.addAction(self.actionIndia_States)
        self.menuChoroplethsBySpecies.addAction(self.actionGB_Counties)
        self.menuChoroplethsBySpecies.addAction(self.actionWorld_Countries)
        self.menuChoroplethsByChecklists.addAction(self.actionUS_States_Checklists)
        self.menuChoroplethsByChecklists.addAction(self.actionUS_Counties_Checklists)
        self.menuChoroplethsByChecklists.addAction(self.actionCanada_Provinces_Checklists)
        self.menuChoroplethsByChecklists.addAction(self.actionIndia_States_Checklists)
        self.menuChoroplethsByChecklists.addAction(self.actionGB_Counties_Checklists)
        self.menuChoroplethsByChecklists.addAction(self.actionWorld_Countries_Checklists)
        self.menuChoropleths.addAction(self.menuChoroplethsBySpecies.menuAction())
        self.menuChoropleths.addAction(self.menuChoroplethsByChecklists.menuAction())
        self.menuMaps.addAction(self.actionMap)
        self.menuMaps.addAction(self.menuChoropleths.menuAction())
        self.menuMaps.addAction(self.actionLifeListMap)
        self.menuMaps.addAction(self.actionFirstSightingsMap)
        self.menuMaps.addAction(self.actionEffortMap)
        self.menuMaps.addAction(self.actionEffortMapByChecklists)
        self.menuMaps.addAction(self.actionSpeciesTotalMap)
        self.menuMaps.addAction(self.actionIndividualsTotalMap)
        self.menuBar.addAction(self.menuFile.menuAction())
        self.menuBar.addAction(self.menuFilter.menuAction())
        self.menuBar.addAction(self.menuLists.menuAction())
        self.menuBar.addAction(self.menuReports.menuAction())
        self.menuBar.addAction(self.menuGraphs.menuAction())
        self.menuBar.addAction(self.menuMaps.menuAction())
        self.menuBar.addAction(self.menuPhotos.menuAction())
        self.menuBar.addAction(self.menuWindows.menuAction())
        self.menuBar.addAction(self.menuAbout.menuAction())
        self.menuBar.addAction(self.menuHelp.menuAction())
        self.toolBar.addAction(self.actionOpen)
        self.toolBar.addAction(self.actionPrint)
        self.toolBar.addAction(self.actionCreatePDF)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionClearAllFilters)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionSpecies)
        self.toolBar.addAction(self.actionLocations)
        self.toolBar.addAction(self.actionChecklists)
        self.toolBar.addAction(self.actionMap)
        self.toolBar.addAction(self.actionFamilies)
        self.toolBar.addAction(self.actionDateTotals)
        self.toolBar.addAction(self.actionLocationTotals)
        self.toolBar.addAction(self.actionCompareLists)
        self.toolBar.addAction(self.actionBigReport)
        self.toolBar.addAction(self.actionPhotos)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionFind)
        self.toolBar.addSeparator()

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "eBird Analyzer"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuReports.setTitle(_translate("MainWindow", "Reports"))
        self.menuWindows.setTitle(_translate("MainWindow", "Windows"))
        self.menuMap.setTitle(_translate("MainWindow", "Map"))
        self.menuLists.setTitle(_translate("MainWindow", "Lists"))
        self.menuAbout.setTitle(_translate("MainWindow", "About"))
        self.menuHelp.setTitle(_translate("MainWindow", "User Guide"))
        self.menuFilter.setTitle(_translate("MainWindow", "Filter"))
        self.menuPhotos.setTitle(_translate("MainWindow", "Photos"))
        self.menuMaps.setTitle(_translate("MainWindow", "Maps"))
        self.menuChoropleths.setTitle(_translate("MainWindow", "Shaded Regions"))
        self.menuChoroplethsBySpecies.setTitle(_translate("MainWindow", "By Species"))
        self.menuChoroplethsByChecklists.setTitle(_translate("MainWindow", "By Checklists"))
        self.menuGraphs.setTitle(_translate("MainWindow", "Graphs"))
        self.menuGraphsSpecies.setTitle(_translate("MainWindow", "Species"))
        self.menuGraphsLocations.setTitle(_translate("MainWindow", "Locations"))
        self.menuGraphsChecklists.setTitle(_translate("MainWindow", "Checklists"))
        self.menuGraphsTiming.setTitle(_translate("MainWindow", "Timing && Seasonality"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.dckFilter.setWindowTitle(_translate("MainWindow", "Sighting Filter"))
        self.lblCountries_2.setText(_translate("MainWindow", "Region"))
        self.cboRegions.setToolTip(_translate("MainWindow", "Select a country to limit your search to one country\'s sightings."))
        self.lblCountries.setText(_translate("MainWindow", "Country"))
        self.cboCountries.setToolTip(_translate("MainWindow", "Select a country to limit your search to one country\'s sightings."))
        self.lblStates.setText(_translate("MainWindow", "State"))
        self.cboStates.setToolTip(_translate("MainWindow", "Select a state to limit your search to one state\'s sightings."))
        self.lblCounties.setText(_translate("MainWindow", "County"))
        self.cboCounties.setToolTip(_translate("MainWindow", "Select a countyto limit your search to one county\'s sightings."))
        self.lblLocations.setText(_translate("MainWindow", "Location"))
        self.cboLocations.setToolTip(_translate("MainWindow", "Select a location to limit your search to one location\'s sightings."))
        self.lblOrders.setText(_translate("MainWindow", "Order"))
        self.cboOrders.setToolTip(_translate("MainWindow", "Select an order to limit your search to sightings of one order."))
        self.lblFamilies.setText(_translate("MainWindow", "Familiy"))
        self.cboFamilies.setToolTip(_translate("MainWindow", "Select a family to limit your search to sightings of one family."))
        self.lblSpecies.setText(_translate("MainWindow", "Species"))
        self.cboSpecies.setToolTip(_translate("MainWindow", "Select a species to limit your search to sightings of one species."))
        self.lblCommonNameSearch.setText(_translate("MainWindow", "Name Search"))
        self.txtCommonNameSearch.setToolTip(_translate("MainWindow", "Enter text that must appear in the common name.  Prepend your text with s: to search the scientific name instead."))
        self.lblEndSeasonalRange_2.setText(_translate("MainWindow", "Date Options"))
        self.cboDateOptions.setToolTip(_translate("MainWindow", "Select a date option to limit your search."))
        self.cboYear.setToolTip(_translate("MainWindow", "Select a year to filter by."))
        self.lblStartDate.setText(_translate("MainWindow", "Start Date"))
        self.calStartDate.setToolTip(_translate("MainWindow", "Select a start date."))
        self.calStartDate.setDisplayFormat(_translate("MainWindow", "yyyy-MM-dd"))
        self.lblEndDate.setText(_translate("MainWindow", "End Date"))
        self.calEndDate.setToolTip(_translate("MainWindow", "Select an end date."))
        self.calEndDate.setDisplayFormat(_translate("MainWindow", "yyyy-MM-dd"))
        self.lblEndSeasonalRange_3.setText(_translate("MainWindow", "Seasonal Range Options"))
        self.cboSeasonalRangeOptions.setToolTip(_translate("MainWindow", "Select a seasonal range, such as a time of year."))
        self.lblStartSeasonalRange.setText(_translate("MainWindow", "Start Seasonal Range"))
        self.cboStartSeasonalRangeMonth.setToolTip(_translate("MainWindow", "Select the starting seasonal range\'s month."))
        self.cboStartSeasonalRangeDate.setToolTip(_translate("MainWindow", "Select the starting seasonal range\'s date."))
        self.lblEndSeasonalRange.setText(_translate("MainWindow", "End Seasonal Range"))
        self.cboEndSeasonalRangeMonth.setToolTip(_translate("MainWindow", "Select the ending seasonal range\'s month."))
        self.cboEndSeasonalRangeDate.setToolTip(_translate("MainWindow", "Select the ending seasonal range\'s date."))
        self.dckPhotoFilter.setWindowTitle(_translate("MainWindow", "Photo Filter"))
        self.lblSighting.setText(_translate("MainWindow", "Rating Range"))
        self.cboStartRatingRange.setToolTip(_translate("MainWindow", "Specify the lowest f-stop aperture for a range of apertures."))
        self.cboEndRatingRange.setToolTip(_translate("MainWindow", "Specify the highest f-stop aperture for a range of apertures."))
        self.lblSpeciesHasPhoto.setText(_translate("MainWindow", "Species"))
        self.cboSpeciesHasPhoto.setToolTip(_translate("MainWindow", "Specify whether a species must\n"
"have a photo attached for the other\n"
"filters\' circumstances.\n"
"(You don\'t need to set this\n"
"if you set other camera filters.)"))
        self.lblCamera.setText(_translate("MainWindow", "Camera"))
        self.cboCamera.setToolTip(_translate("MainWindow", "Specify a camera model."))
        self.lblLens.setText(_translate("MainWindow", "Lens"))
        self.cboLens.setToolTip(_translate("MainWindow", "Specify a lens model."))
        self.lblShutterSpeedRange.setText(_translate("MainWindow", "Shutter Speed Range"))
        self.cboStartShutterSpeedRange.setToolTip(_translate("MainWindow", "Specify the shortest shutter speed for a range of shutter speeds."))
        self.cboEndShutterSpeedRange.setToolTip(_translate("MainWindow", "Specify the longest shutter speed for a range of shutter speeds."))
        self.lblApertureRange.setText(_translate("MainWindow", "Aperture Range"))
        self.cboStartApertureRange.setToolTip(_translate("MainWindow", "Specify the lowest f-stop aperture for a range of apertures."))
        self.cboEndApertureRange.setToolTip(_translate("MainWindow", "Specify the highest f-stop aperture for a range of apertures."))
        self.lblFocalLengthRange.setText(_translate("MainWindow", "Focal Length Range"))
        self.cboStartFocalLengthRange.setToolTip(_translate("MainWindow", "Specify the shortest focal length for a range of focal lengths."))
        self.cboEndFocalLengthRange.setToolTip(_translate("MainWindow", "Specify the longest focal length for a range of focal lengths."))
        self.lblISORange.setText(_translate("MainWindow", "ISO Range"))
        self.cboStartIsoRange.setToolTip(_translate("MainWindow", "Specify the lowest ISO number for a range of ISO numbers."))
        self.cboEndIsoRange.setToolTip(_translate("MainWindow", "Specify the highest ISO number for a range of ISO numbers."))
        self.actionOpen.setText(_translate("MainWindow", "Open eBird data file..."))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionDateTotals.setText(_translate("MainWindow", "Date Totals"))
        self.actionLocationTotals.setText(_translate("MainWindow", "Location Totals"))
        self.actionTileWindows.setText(_translate("MainWindow", "Tile Windows"))
        self.actionCloseAllWindows.setText(_translate("MainWindow", "Close All Windows"))
        self.actionCompareLists.setText(_translate("MainWindow", "Compare Lists"))
        self.actionCascade.setText(_translate("MainWindow", "Cascade Windows"))
        self.actionSpecies.setText(_translate("MainWindow", "Species"))
        self.actionLocations.setText(_translate("MainWindow", "Locations"))
        self.actionChecklists.setText(_translate("MainWindow", "Checklists"))
        self.actionBigReport.setText(_translate("MainWindow", "Big Report"))
        self.actionBigReport.setToolTip(_translate("MainWindow", "Big Report"))
        self.actionStats.setText(_translate("MainWindow", "Statistics"))
        self.actionStats.setToolTip(_translate("MainWindow", "Overall statistics for the current filter"))
        self.actionBarGraph.setText(_translate("MainWindow", "Total Species"))
        self.actionBarGraph.setToolTip(_translate("MainWindow", "Total species per year as a bar graph"))
        self.actionCumulativeCurve.setText(_translate("MainWindow", "Species Growth Over Time"))
        self.actionCumulativeCurve.setToolTip(_translate("MainWindow", "Running total of species seen over time"))
        self.actionCumulativeLocations.setText(_translate("MainWindow", "Locations Growth Over Time"))
        self.actionCumulativeLocations.setToolTip(_translate("MainWindow", "Running total of distinct locations visited over time"))
        self.actionCumulativeFamilies.setText(_translate("MainWindow", "Families Growth Over Time"))
        self.actionCumulativeFamilies.setToolTip(_translate("MainWindow", "Running total of bird families seen over time"))
        self.actionHeatmap.setText(_translate("MainWindow", "Monthly Activity"))
        self.actionHeatmap.setToolTip(_translate("MainWindow", "Species count by month and year"))
        self.actionAccumulation.setText(_translate("MainWindow", "New Species Each Year"))
        self.actionAccumulation.setToolTip(_translate("MainWindow", "New species added each year vs. repeats"))
        self.actionTopLocations.setText(_translate("MainWindow", "Top Locations by Species"))
        self.actionTopLocations.setToolTip(_translate("MainWindow", "Top 20 locations by species count"))
        self.actionYTDReport.setText(_translate("MainWindow", "Year to Date by Species"))
        self.actionYTDReport.setToolTip(_translate("MainWindow", "Species seen this year vs. full-year totals for previous years"))
        self.actionYTDLocations.setText(_translate("MainWindow", "Year to Date by Locations"))
        self.actionYTDLocations.setToolTip(_translate("MainWindow", "Locations visited this year vs. full-year totals for previous years"))
        self.actionYTDChecklists.setText(_translate("MainWindow", "Year to Date by Checklists"))
        self.actionYTDChecklists.setToolTip(_translate("MainWindow", "Checklists submitted this year vs. full-year totals for previous years"))
        self.actionTotalChecklists.setText(_translate("MainWindow", "Total Checklists"))
        self.actionTotalChecklists.setToolTip(_translate("MainWindow", "Total checklists per period as a bar graph"))
        self.actionTotalLocations.setText(_translate("MainWindow", "Total Locations"))
        self.actionTotalLocations.setToolTip(_translate("MainWindow", "Total distinct locations per period as a bar graph"))
        self.actionScatter.setText(_translate("MainWindow", "Outing Effort"))
        self.actionScatter.setToolTip(_translate("MainWindow", "Species count vs. time spent per outing, coloured by season"))
        self.actionPhenology.setText(_translate("MainWindow", "Seasonal Occurrence"))
        self.actionPhenology.setToolTip(_translate("MainWindow", "When each species is recorded through the year — best with a species filter"))
        self.actionFOY.setText(_translate("MainWindow", "First of Year Chart"))
        self.actionFOY.setToolTip(_translate("MainWindow", "First sighting of each species per year, plotted by month"))
        self.actionLOY.setText(_translate("MainWindow", "Last of Year Chart"))
        self.actionLOY.setToolTip(_translate("MainWindow", "Last sighting of each species per year, plotted by month"))
        self.actionLocationScatter.setText(_translate("MainWindow", "Location Productivity"))
        self.actionLocationScatter.setToolTip(_translate("MainWindow", "Locations compared by species count vs. number of visits"))
        self.actionSpeciesScatter.setText(_translate("MainWindow", "Species Breadth"))
        self.actionSpeciesScatter.setToolTip(_translate("MainWindow", "Species compared by how many locations they have been seen at vs. total individuals counted"))
        self.actionLocationChecklistPie.setText(_translate("MainWindow", "Locations by Checklists"))
        self.actionLocationChecklistPie.setToolTip(_translate("MainWindow", "Checklist count by location as a pie chart"))
        self.actionFamilyPie.setText(_translate("MainWindow", "Families && Orders by Species"))
        self.actionFamilyPie.setToolTip(_translate("MainWindow", "Species count by family or order as a pie chart"))
        self.actionIndivPie.setText(_translate("MainWindow", "Families && Orders by Individual Count"))
        self.actionIndivPie.setToolTip(_translate("MainWindow", "Observed individual count by family or order as a pie chart"))
        self.actionFind.setText(_translate("MainWindow", "Find"))
        self.actionFamilies.setText(_translate("MainWindow", "Pie Charts"))
        self.actionMap.setText(_translate("MainWindow", "Map"))
        self.actionCreatePDF.setText(_translate("MainWindow", "Create PDF"))
        self.actionPrint.setText(_translate("MainWindow", "Print"))
        self.actionAboutYearbirder.setText(_translate("MainWindow", "About Yearbirder"))
        self.actionUserGuide.setText(_translate("MainWindow", "User Guide"))
        self.actionShowStandardFilter.setText(_translate("MainWindow", "Show sighting filter"))
        self.actionHideStandardFilter.setText(_translate("MainWindow", "Hide sighting filter"))
        self.actionHideStandardFilter.setToolTip(_translate("MainWindow", "Hide sighting filter"))
        self.actionClearAllFilters.setText(_translate("MainWindow", "Clear all filters"))
        self.actionSetPhotoFolder.setText(_translate("MainWindow", "Set Photo Folder"))
        self.actionPhotos.setText(_translate("MainWindow", "Photos"))
        self.actionPhotosByFilter.setText(_translate("MainWindow", "Browse Photos"))
        self.actionSpeciesGallery.setText(_translate("MainWindow", "Species Gallery"))
        self.actionEditPhotosByFilter.setText(_translate("MainWindow", "Manage Photos..."))
        self.actionOpenPhotoSettings.setText(_translate("MainWindow", "Open photo catalog..."))
        self.actionAddPhotos.setText(_translate("MainWindow", "Add photos..."))
        self.actionSavePhotoSettings.setText(_translate("MainWindow", "Save photo catalog..."))
        self.actionPreferences.setText(_translate("MainWindow", "Preferences..."))
        self.actionUpdateEXIFDataForAllPhotos.setText(_translate("MainWindow", "Re-read camera data from all photos"))
        self.actionRenamePhotos.setText(_translate("MainWindow", "Rename photos..."))
        self.actionOptimizePhotoSettings.setText(_translate("MainWindow", "Compact photo catalog..."))
        self.actionShowPhotoFilter.setText(_translate("MainWindow", "Show photo filter"))
        self.actionHidePhotoFilter.setText(_translate("MainWindow", "Hide photo filter"))
        self.actionClearPhotoFilter.setText(_translate("MainWindow", "Clear photo filter"))
        self.actionClearStandardFilter.setText(_translate("MainWindow", "Clear sighting filter"))
        self.actionClose.setText(_translate("MainWindow", "Close eBird data file"))
        self.actionClosePhotoSettings.setText(_translate("MainWindow", "Close photo catalog"))
        self.actionUS_States.setText(_translate("MainWindow", "US States"))
        self.actionWorld_Countries.setText(_translate("MainWindow", "World Countries"))
        self.actionWorld_Subregion_1.setText(_translate("MainWindow", "World Subregion 1"))
        self.actionUS_Counties.setText(_translate("MainWindow", "US Lower 48 Counties"))
        self.actionCanada_Provinces.setText(_translate("MainWindow", "Canada Provinces"))
        self.actionIndia_States.setText(_translate("MainWindow", "India States"))
        self.actionGB_Counties.setText(_translate("MainWindow", "Great Britain Counties"))
        self.actionUS_States_Checklists.setText(_translate("MainWindow", "US States"))
        self.actionUS_Counties_Checklists.setText(_translate("MainWindow", "US Lower 48 Counties"))
        self.actionCanada_Provinces_Checklists.setText(_translate("MainWindow", "Canada Provinces"))
        self.actionIndia_States_Checklists.setText(_translate("MainWindow", "India States"))
        self.actionGB_Counties_Checklists.setText(_translate("MainWindow", "Great Britain Counties"))
        self.actionWorld_Countries_Checklists.setText(_translate("MainWindow", "World Countries"))
        self.actionGeolocatedPhotos.setText(_translate("MainWindow", "Geolocated Photos"))
        self.actionAnimatedPhotoSequence.setText(_translate("MainWindow", "Animated Sequence Map"))
        self.actionSlideshow.setText(_translate("MainWindow", "Slideshow"))
        self.actionYTDPhotos.setText(_translate("MainWindow", "Year to Date by Photographs"))
        self.actionYTDPhotos.setToolTip(_translate("MainWindow", "Photos taken this year vs. full-year totals for previous years"))
        self.actionPhotoPie.setText(_translate("MainWindow", "Families && Orders by Photos"))
        self.actionPhotoPie.setToolTip(_translate("MainWindow", "Photo count by family or order as a pie chart"))
        self.actionPhotoBar.setText(_translate("MainWindow", "Total Photos"))
        self.actionPhotoBar.setToolTip(_translate("MainWindow", "Total photos per time period"))
        self.actionPhotoAccumulation.setText(_translate("MainWindow", "New Species Photographed Each Year"))
        self.actionPhotoAccumulation.setToolTip(_translate("MainWindow", "New species photographed each year vs. already photographed"))
        self.actionCumulativePhotos.setText(_translate("MainWindow", "Photographed Species Growth Over Time"))
        self.actionCumulativePhotos.setToolTip(_translate("MainWindow", "Running total of species ever photographed over time"))
        self.actionLifeListMap.setText(_translate("MainWindow", "Animated Lifers"))
        self.actionFirstSightingsMap.setText(_translate("MainWindow", "Animated First Sightings"))
        self.actionEffortMap.setText(_translate("MainWindow", "Bubble by Time"))
        self.actionEffortMapByChecklists.setText(_translate("MainWindow", "Bubble by Checklists"))
        self.actionSpeciesTotalMap.setText(_translate("MainWindow", "Bubble by Species"))
        self.actionIndividualsTotalMap.setText(_translate("MainWindow", "Bubble by Bird Count"))
import icons_rc
